from locust import HttpUser, task, between
import random

# --- Configuration area ---
# Must match the ID range generated by your Python script
# We set 20000 entries per shard, assuming you only connected one shard or IDs are continuous
# Suggest setting a larger range to cover your test data
MIN_USER_ID = 1
MAX_USER_ID = 20000 

class CouponQueryUser(HttpUser):
    # Simulate each user thinking 0.5 ~ 2 seconds between requests
    # If you want to test extreme pressure, you can reduce this time, e.g., between(0.01, 0.1)
    wait_time = between(0.5, 2)

    @task
    def query_coupon_logic(self):
        user_id = random.randint(MIN_USER_ID, MAX_USER_ID)
        
        with self.client.get(f"/api/coupons/{user_id}", catch_response=True) as response:
            # Get Header returned by backend
            cache_status = response.headers.get("X-Cache", "UNKNOWN")
            
            # Dynamically modify the name in Locust statistics!
            # This way you'll see two rows in the UI: "Coupon [HIT]" and "Coupon [MISS]"
            response.request_meta["name"] = f"Coupon [{cache_status}]"

# If you want to directly run python locustfile.py (for debugging)
if __name__ == "__main__":
    import os
    os.system("locust -f locustfile.py")